maxRecentLogLines: 0
alert:
  slack:
    webhook: ""
  pagerduty:
    integrationKey: ""
  discord:
    webhook: ""
  telegram:
    token: ""
    chatId: ""
  email:
    form: ""
    password: ""
    host: ""
    port: ""
    to: ""
  teams:
    webhook: ""
  rocketchat:
    webhook: ""
namespaces:
  - default